=== uthraE/E-Bazaar/bazaar/src/main/resources/api/schemas/e-bazaar-api-response-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "product_name",
      "product_id",
      "type",
      "metric",
      "brand",
      "price"
    ],
    "properties": {
      "product_name": {
        "$id": "#/items/properties/product_name",
        "type": "string",
        "title": "The Product_name Schema",
        "default": "",
        "examples": [
          "carrot"
        ],
        "pattern": "^(.*)$"
      },
      "product_id": {
        "$id": "#/items/properties/product_id",
        "type": "string",
        "title": "The Product_id Schema",
        "default": "",
        "examples": [
          "V_34748"
        ],
        "pattern": "^(.*)$"
      },
      "type": {
        "$id": "#/items/properties/type",
        "type": "string",
        "title": "The Type Schema",
        "default": "",
        "examples": [
          "vegetable"
        ],
        "pattern": "^(.*)$"
      },
      "metric": {
        "$id": "#/items/properties/metric",
        "type": "string",
        "title": "The Metric Schema",
        "default": "",
        "examples": [
          "kg"
        ],
        "pattern": "^(.*)$"
      },
      "brand": {
        "$id": "#/items/properties/brand",
        "type": "string",
        "title": "The Brand Schema",
        "default": "",
        "examples": [
          "NA"
        ],
        "pattern": "^(.*)$"
      },
      "price": {
        "$id": "#/items/properties/price",
        "type": "integer",
        "title": "The Price Schema",
        "default": 0,
        "examples": [
          30
        ]
      }
    }
  }
}

=== uthraE/E-Bazaar/bazaar/src/test/resources/sample_data/list_json_1.json
[
    {
      "product_name" : "carrot",
      "product_id" : "V_34748",
      "type" :  "vegetable",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 30
    },
    {
      "product_name" : "Beans",
      "type" :  "vegetable",
      "product_id" : "V_34749",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 10
    },
    {
      "product_name" : "Brinjal",
      "type" :  "vegetable",
      "product_id" : "V_34750",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 5
    },
    {
      "product_name" : "Potatoe",
      "product_id" : "V_34800",
      "type" :  "vegetable",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 30
    },
    {
      "product_name" : "Apple",
      "product_id" : "F_20001",
      "type" :  "Fruits",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 20
    },
    {
      "product_name" : "Orange",
      "product_id" : "F_20011",
      "type" :  "Fruit",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 10
    },
    {
      "product_name" : "Grape",
      "product_id" : "F_20021",
      "type" :  "Fruit",
      "metric" : "kg",
      "brand" : "NA",
      "price" : 30
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10001",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Casio",
      "price" : 100
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10002",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Micra",
      "price" : 150
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10003",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Photon",
      "price" : 250
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10004",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Galio",
      "price" : 250
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10005",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Photon",
      "price" : 250
    },
    {
      "product_name" : "Calculator",
      "product_id" : "E_10006",
      "type" :  "Electronics",
      "metric" : "NA",
      "brand" : "Photon",
      "price" : 250
    }
]
